apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-lab-web-ingress
  labels:
    app.kubernetes.io/name: news-lab-web
    app.kubernetes.io/part-of: newslab
spec:
  ingressClassName: traefik
  rules:
    - host: newslab.ai.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: news-lab-web
                port:
                  number: 80
    - host: www.newslab.ai.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: news-lab-web
                port:
                  number: 80
